# Generated by Django 3.2 on 2023-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
