# Generated by Django 3.2 on 2023-03-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_default_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
