# Generated by Django 3.2 on 2023-03-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
    ]
