# Generated by Django 3.2 on 2023-03-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='average_rating',
            new_name='rating',
        ),
    ]
